### ISSUE TITLE
error: System.Net.Mail.SmtpException

### ISSUE THREAD

**Issue by icarus342** [mystborn/DiscordTextbot#2]
Getting the following error when trying to send a message.

`The message to 10digit#@vtext.com encountered an error: System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)`

No errors in running the bot itself, just get this error as a response in discord.

**Comment by icarus342** [comment]
Just a follow up, I did try sending an email to the phone number address I already tried and it worked fine, but still getting this error when running the bot with the same email.

**Comment by icarus342** [comment]
Figured out the problem, changed the default port in the config from 465 to 587 for gmail.
